#!/usr/bin/env sh

set -x
clean() {
	sed 's/^package://' | sed 's/\r$//'
}
app_domain() {
	adb shell pm list packages | clean | fzf --query="$1"
}

apk_path() {
	adb shell pm path "$1" | clean | head -1
}

adb pull "$(apk_path "$(app_domain $1)")"
