#!/usr/bin/env sh

clean() {
	sed 's/^package://' | head -1
}
app_domain() {
	adb shell cmd package list packages | fzf | clean
}

apk_path() {
	adb shell pm path "$1" | clean
}

adb pull "$(apk_path "$(app_domain $1)")" "$1.apk"
