#!/usr/bin/env sh

MNT="/tmp/CamMount"

die(){
	echo [0m[31m$@ >&2[0m
	unmount
	exit 1
}
pull_all() {
	shopt -s globstar
	set -x
	rsync --verbose --progress --remove-source-files --no-relative --no-implied-dirs \
		"$(mount)"/** ${1:-"."} &&
	set +x
	unmount
}

mount() {
	mkdir -p $MNT &&
	gphotofs $MNT &&
	while ! ls $MNT >/dev/null
		do sleep 1
	done
	echo $MNT
}

unmount() {
	fusermount -u $MNT
	rmdir $MNT
}

get_newest() {
	set -x
	find "$(mount)" -type f -iname '*.JPG' | xargs ls -t | head -1 | xargs cat | magick jpg:- -identify -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG latest.jpg &&
	dragon latest.jpg &&
	unmount
}

show_help() {
	echo "Available Commands:"
	declare -F | awk '{print "- "$3}'
	exit 1
}

test -z "$1" && show_help
cmd=$1
shift
$cmd $@
