#!/usr/bin/env sh
#set -x

color_replace() {
	match="$@"
	replace=`echo $match | lolcat -F 0.05 -f`
	echo "s/$match/$replace/g"
}

sedcmd() {
    for match in $@; do
    	color_replace "$match"
    done | tr '\n' ';'
}

sed `sedcmd $@`


