#!/usr/bin/env sh

_compress_jpg() {
    NAME="$(dirname $1)/~$(basename $1)"
    convert "$1" -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG "$NAME"

}

for f in "$@"; do
	_compress_jpg "$f"
done

