#!/usr/bin/env sh

: ${XDG_CONFIG_HOME:=$HOME/.config}

menu_cmd() {
	INPUT=$( cat )
	echo "$INPUT" | umenu -sq ||
	echo "$INPUT" | fzf ||
	{ command -v fzf >/dev/null 2>&1 || echo "$INPUT" | head -1; }
}

FILE=$(
	find $XDG_CONFIG_HOME -maxdepth 1 -name "*$1*" |
	while read -r RESULT; do find "$RESULT" -type f; done |
	sort -r | uniq |
	grep -v '.git' |
	menu_cmd
)

if [ -n "$FILE" ]; then
	exec $EDITOR "$FILE"
fi
