#!/usr/bin/env sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

idisplay=`xrandr --listmonitors | grep -o 'eDP[-1]*' | head -n1`
edisplays="$(
	xrandr --listmonitors |
	sed -E '1d;s/ .+? .+? .+? //' |
	grep -v "$idisplay" |
	tr '\n' ' '
)"

xrandr --output $idisplay --auto --mode 3840x2160
arrange() {
	test -z "$1" && return
	d0=$1
	xrandr --output $1 --auto --rotate normal --primary --above $idisplay
	shift
	test -z "$1" && return
	xrandr --output $1 --auto --rotate normal --right-of $d0
	shift
	test -z "$1" && return
	xrandr --output $1 --auto --rotate normal --left-of $d0
}
arrange $edisplays
xwallpaper --no-randr --center ~/media/images/wallpapers/pscrn2023-12-02_154008.png

xinput map-to-output 'ATML1000:00 03EB:8A79' $idisplay
xinput map-to-output 'Wacom HID 16C Pen eraser' $idisplay
xinput map-to-output 'Wacom HID 16C Pen stylus' $idisplay
xinput --set-prop 'Wacom HID 16C Pen stylus' 'Wacom button action 1' 1572867
xinput --set-prop 'Wacom HID 16C Pen eraser' 'Wacom button action 0' 1572866
xinput --set-prop 'Wacom HID 16C Pen stylus' 'Wacom button action 0' 1572865

xinput --list | sed -E '1d;/keyboard/{d;q};s/.*id=([0-9]+).*/\1/' | while read pointer_id; do
	xinput set-prop $pointer_id 'Device Accel Constant Deceleration' 2
done

xset r rate 180 50
