#!/bin/bash

#TODO make the -mount option a user preference
finddeploy() {
	find $1 -mount -name ".deploy" 2>/dev/null | tr '\n' ' '
}

rsync_args() {
	echo "--recursive --update --executability --human-readable --progress"
}

build_longargs(){
	awk -F ':' '{
 		for (i=1; i<=NF; i++)
			printf "--'$argstring'='"'"'"$i"'"'"' "
	}'
}

rsync_exclude() {
	( argstring=exclude; echo "$@" | build_longargs )
}

rsync_include() {
	( argstring=include; echo "$@" | build_longargs )
}

rsync_host() {
	test -v 
}

#convert an xdg user directory to its root equivalent and vice-versa
xdg_dir_convert() {
	if [ "$1" -ef "$XDG_CONFIG_DIRS" ]; then
		echo "$XDG_CONFIG_HOME"
	elif [ "$1" -ef "$XDG_CACHE_DIRS" ]; then
		echo "$XDG_CACHE_HOME"
	elif [ "$1" -ef "$XDG_DATA_DIRS" ]; then
		echo "$XDG_DATA_HOME"
	elif [ "$1" -ef "$XDG_CONFIG_HOME" ]; then
		echo "$XDG_CONFIG_DIRS"
	elif [ "$1" -ef "$XDG_CACHE_HOME" ]; then
		echo "$XDG_CACHE_DIRS"
	elif [ "$1" -ef "$XDG_DATA_HOME" ]; then
		echo "$XDG_DATA_DIRS"
	else
		return 1
	fi
}

#true of the given file is within the HOME of its owner
is_user_file() {
	usr=$(stat -c '%U' $1)
	realpath $1 | grep -E "^$(eval echo "~$usr")"
}

deploy_dir() { #takes path to .deploy file as argument
	set -u
	src="$(dirname $1)/"
	source $1

	#there are 4 possible modes for deployment: user to root, user to user, root to root, root to user
	#for now, only user to root is being implemented
	#TODO add ROOTEXCLUDE, ROOTINCLUDE, USEREXCLUDE, USERINCLUDE
	test -v ROOTDIR ||
	ROOTDIR="$(xdg_dir_convert $src/..)/$(basename $src)" || {
		echo "Could not resolve destination for $src"
		return 1
	}
	dest="$ROOTDIR"

	{	rsync_include $(test -v INCLUDE && echo $INCLUDE)
		rsync_exclude $(test -v EXCLUDE && echo $EXCLUDE):.deploy
		rsync_args
		echo "$src kico:$dest"
	} | xargs rsync
}

while getopts ":u:h" opt; do
	case $opt in
		u)
			user="$OPTARG"
			;;
		h)
			echo "you are beyond help"
			exit
			;;
		:)
			echo "Option -$OPTARG requires an argument" >&2
			exit 1
			;;
	esac
done

for d in $(finddeploy); do
	(deploy_dir $d)
done
