#!/bin/sh 

while true; do
if [ -z ${DISPLAY+x} ]; then exit
fi
addtostatus() 
{
	delim=' | '
	barstatus=$@$delim$barstatus
}

barstatus=$(date +%a' '%m-%d' '%H:%M:%S)

audioname=$(pulsemixer --list-sinks | grep Default | awk '{print $5}' | tr -d ".,")
audiolevel=$(pulsemixer --get-volume | awk '{print $1}')
addtostatus " $audioname $audiolevel%"

addtostatus "$(bl)%"

#acpi | awk '{print $3" "$4}' | tr -d "%," | read 'batstat' 'batlevel'
addtostatus "$(acpi | sed 1q | awk '{print $4}' | tr -d ',' )"

xsetroot -name "$barstatus"
sleep 5s
done &
