#!/bin/sh 
addtostatus() 
{
	delim=' | '
	barstatus=$@$delim$barstatus
}
while :; do
barstatus=$(date +%a' '%m-%d' '%H:%M:%S)

sinkname=$(pactl info | sed -n 13p | awk '{print $3}')
addtostatus "$(pactl list sinks | sed -n "/$sinkname/{n;p;n;n;n;n;n;n;p;q}" | tr -d '\n' | awk '{print ""$2" "$(NF-3)}')"

addtostatus "$(light | awk -F '.' '{print $1}')%"

addtostatus "$(acpi | sed 1q | awk '{print $4}' | tr -d ',' )"

xsetroot -name "$barstatus"
sleep 1s
done &
