#!/usr/bin/env sh

#https://xkcd.com/1168/
extract_one() {
	set -f
	case 	"$f" in
		*.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf "$f";;
		*.tar.gz|*.tgz) tar xzvf "$f";;
		*.tar.xz|*.txz) tar xJvf "$f";;
		*.zip|*.jar) unzip "$f";;
		*.rar) unrar x "$f";;
		*.7z) 7z x "$f";;
	esac
}

for f in "$@"; do
	echo $f
	extract_one "$f"
done

