#!/usr/bin/env sh
label="Arch Linux"
kernel_params=$( tr '\n' ' ' < /etc/kernel-params.conf )
efibootmgr -B -b $(efibootmgr | grep "$label" | awk -F '' '{print $5 $6 $7 $8}')
efibootmgr --disk /dev/sda --part 1 --create --label  "$label" --loader /vmlinuz-linux --unicode "$kernel_params" --verbose

