#!/usr/bin/env sh

is_git_base() {
	test -n "$1" && testpath="$@" || testpath="."
	test -e $(realpath "$testpath")/.git
}

go_to_git_base() {
	wd="`pwd`"
	while ! is_git_base && [ `pwd` != "/" ]; do
		cd ..
	done
	if ! is_git_base; then
		cd "$wd"
		echo "no \".git\" found" >&2
		false
	fi
}
	
git_staged() {
	#list staged files, error if empty
	git diff --cached --name-only | grep .
}

last_commit_time() {
	git show --pretty=format:"%at" HEAD | head -n 1
}

