#!/bin/sh

confdir=/usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
option='Option "PrimaryGPU"'


if [ "$(grep "#$option" $confdir)" ]; then
	echo 'swtiching to dedicated graphics'
	sedcmd=s/\#$option/$option/
else 
	echo 'swtiching to integrated graphics'
	sedcmd=s/$option/\#$option/
fi

sed "$sedcmd" $confdir > $confdir.new
mv $confdir.new $confdir
