#!/usr/bin/env sh

err() {
	echo "$(color red)$@$(color off)" >&2
}
warn() {
	echo "$(color blue)$@$(color off)" >&2
}
die() {
	err $@
	exit 1
}
die() {
	warn "addtodir [files]"
}

_addtodir() {
	mv -n "$1" "$TODIR"
}

while [ $# -gt 0 ]; do
	case "$1" in
		-q|--quiet)
			warn(){ :; }
			shift
			;;
		-o|--option)
			shift 
			set -u; OPTION=$1; set +u
			shift
			;;
		--)
			shift
			break
			;;
		*)
			break
			;;
	esac
done

: ${TODIR:=$1}
: ${TODIR:=$(pwd)}
mkdir -p "$TODIR"

if read -t 0; then while read line; do
	_addtodir "$line"
done fi

for f in "$@"; do
	_addtodir "$f"
done
