#!/usr/bin/env bash

test $UID -eq 0 &&
	template_lib="$XDG_DATA_DIRS/new" ||
	template_lib="$XDG_DATA_HOME/new"

extension() { basename "$1" | awk -F '.' '{print $NF}';}
nextension() {
	basename "$1" |
	awk -F '.' '{
		if($1 != "")
			{ print $1 }
		else 
			{ print $2 }
	}'
}

ldir() { find "$1" -maxdepth 1 ! -path "$1";}

find_template() {
	template="$(dirname "$1")/.TEMP"

	#pick a file from the template library with a matching extension
	test -e "$template" || template="$(
		ldir "$template_lib" |
		grep "$(extension $1)$" |
		umenu -s
	)"

	#pick any file from the template library
	test -e "$template" || template="$(
		ldir "$template_lib" |
		umenu -s
	)"

	test -e "$template" && echo "$template" || {
		echo "Error, no template files found" >&2
		exit 1
	}
}

edit_template() {
	$EDITOR "$(find_template $1)"
}

make_new() {
	template=$(find_template $1)

	test -e "$1" || {
		cp $template $1 #ensures that permissions are copied
			sub="$(nextension $1)"
		sed -i "s/TEMP/$sub/g" "$1"
	}
	$EDITOR "$1"
}

if [ "$1" = '-e' ]; then
	edit_template "$2"
elif [ -n "$1" ]; then
	make_new "$1"
elif [ -n "`xclip -selection clipboard -o`" ]; then
	make_new "`xclip -selection clipboard -o`"
else
	make_new "test"
fi

