#!/usr/bin/env sh

#TODO eliminate the loop and take advantage of stream editing
ls | while read -r FILE; do
	mv -n "$FILE" `
		echo $FILE |
		sed '
			s/\(.*\)/\L\1/;
			s/jpeg/jpg/;
			y/ _/--/;
			s/--[-]*/-/g;
			s/^-//;
			s/://g
		'|
		tr -d \'\"
	`
done
