#!/usr/bin/env sh

NOITAPATH="$STEAM_DIR/steamapps/compatdata/881100/pfx/drive_c/users/steamuser/AppData/LocalLow/Nolla_Games_Noita"

test -n "$1" &&
	SAVENAME="$1" || {
		echo -n "name of new save: ";
		read SAVENAME
	}

pgrep noita.exe >/dev/null && {
	echo -n "waiting for Noita to close"
	sleep 1
	while pgrep noita.exe >/dev/null; do
		echo -n '.'
		sleep 1
	done
	echo
}

cp -r  "$NOITAPATH/save00" "$NOITAPATH/$SAVENAME"
echo "saved $SAVENAME"
