#!/usr/bin/env sh
# pours out the contents of a directory into the parent directory and deletes the empty directory

for DIR in "$@"; do
	if [ -d "$DIR" ]; then
		find "$DIR" -maxdepth 1 -mindepth 1 -execdir mv -n '{}' .. \;
		rmdir "$DIR"
	fi
done
