#!/usr/bin/env sh

eval "$(xdotool getactivewindow getwindowgeometry --shell)"
echo okay go
# capture system audio from the monitor of the default sink
ffmpeg -video_size "$WIDTH"x"$HEIGHT" -f x11grab -i :0.0+$X,$Y \
	-f pulse -i @DEFAULT_MONITOR@ \
	-vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" \
	-c:v libx264 -preset ultrafast -pix_fmt yuv420p -c:a aac \
	"screenrec-$(date +%s).mp4"
