#!/usr/bin/env sh


FILENAME="$1$(date +%F_%H%M%S).png"
test -e "$SCREENSHOTS" &&
	FILENAME="$SCREENSHOTS/$FILENAME"

cat /dev/stdin > $FILENAME
xclip -selection clipboard -target image/png -i "$FILENAME"
ln -sf "$FILENAME" "$HOME/shot.png"
notify-send "Screenshot" "$FILENAME" -i "$FILENAME"

