#!/bin/sh
git checkout master
make clean && git reset --hard origin/master && rm -f config.h
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	if [ "$branch" != "master" ];then
		echo $branch
		git merge $branch -m $branch
	fi
done
sudo make clean install
