#!/usr/bin/env sh

#convert a video to an audio file with thumbnail

audio_type() {
    	echo mp3 #not all audio streams support thumbnails and ffmpeg tends to give some very cryptic error messages when you try, so I'm hardcoding mp3 until I have a better idea
	#ffprobe "$1" -loglevel error -select_streams a -show_entries stream=codec_name | sed -n '2s/^.*=//p'
}
art() {
    	out="${1%.*}.jpg"
	test -e $out ||
	ffmpeg -y -loglevel error -i "$1" -ss 0:0:5 -frames:v 1 "$out"
	echo $out
}
noclobber() {
	test -e "$1" && echo "$(dirname "$1")~$(basename "$1")" || echo $1
}
_thumbnail() {
    	art="$(art "$1")"
	out="${1%.*}.$(audio_type "$1")"
	out_noclobber="$(noclobber "$out")"

	ffmpeg -i "$1" -i "$art" -map 0:a:0 -map 1:0 "$out_noclobber" &&
	rm "$art" &&
	if test "$out" = "$1"; then
    		mv "$out_noclobber" "$1"
    	fi
}

for f in "$@"; do
	_thumbnail "$f"
done

