#!/usr/bin/env sh

list_cameras(){
	v4l2-ctl --list-devices |
	sed -En 's@\s*/dev/media([0-9]*)@\1@p' |
	awk '{print "/dev/video"($1 * 2)}'
}

open_camera(){
	mpv av://v4l2:$1 --profile=low-latency --untimed
	#vlc v4l2://:input-slave=alsa://:v4l-vdev="$1"
}

killem mpv
open_camera `list_cameras | umenu`

#for cam in $(list_cameras); do
	#open_camera $cam  &
#done



